### ISSUE TITLE
Adicionar endpoints para retornar países, províncias e bairros

### ISSUE THREAD

**Issue by acidiney** [acidiney/buscador-ao#3]
# Motivação
Meu objetivo é ter um local que possa abstrair as necessidades recorrentes dos desenvolvedores nas suas apps.

# Objectivo
Quase todo mundo que conheço que é dev sempre pergunta se alguém tem uma lista com países/províncias/bairros.. Eu acredito que você também já ouviu isso ou procurou.
E sim eu sei que já existem soluções para isso, mas acredito que pode ajudar se alguém já está usando o `buscador.ao` pegar essas informações de lá e não ter que consultar uma API terceira ou ter isso internamente no seu projecto.

## Ações a se tomar

- Pegar um json com essas informações e adicionar ao projecto.
- Gerar uma interface para quem deseja fazer uma correção em alguma informação que possa estar incorreta.
- Deixar acessível nos seguintes endpoints:
   - `/countries` -> Retorna todos os países
    - `/countries/:id` -> Retorna o aglomaredado de informações do país, isso inclui também as províncias
    - `/countries/:id/:state` -> Retorna detalhes da província e os municípios
    - `/countries/:id/:state/:city` -> Isso retorna detalhe do municio e os bairros, como também o CEP de cada bairro ( no caso de ser aprovado a outra issue )

## Conclusão

Acredito que isso pode retirar alguma responsabilidade da aplicação e passar para o modulo terceiro

**Comment by JoseCage** [comment]
O endpoint `/countries` foge um pouco da ideia do projeto.

Considerando que que o país seja Angola "sempre" não creio precisares o endpoint. 
🤔🤔

**Comment by acidiney** [comment]
É um bom ponto, talvez não seja necessário agora, a tua sugestão seria não existir esse endpoint e existir somente a possibilidade de recuperar províncias e  municípios é isso? Certo

**Comment by JoseCage** [comment]
> É um bom ponto, talvez não seja necessário agora, a tua sugestão seria não existir esse endpoint e existir somente a possibilidade de recuperar províncias e municípios é isso? Certo

Exatamente.

Sendo que o país seria Angola. Acho que bastava ter apenas os outro endpoints.

Mas é uma questão de analise de caso

**Comment by overlineink** [comment]
Hey @acidiney, muito bom seu projeto :smile: !

Geralmente muitos devs utilizam essa [API](https://github.com/apilayer/restcountries) para isso, seria bom ter algo so nosso. Nesse caso eu concordo com a ideia do @JoseCage em focar em servicos Angolanos (NIF, Geolocalizacao de IPs, ...)

**Comment by acidiney** [comment]
Vou manter por essa linha de raciocínio então.
Vou esperar mais um pouco, para passar para TODO, talvez mais alguém venha para dar a sua opnião

**Comment by acidiney** [comment]
Update: Passou para TODO

**Comment by JoseCage** [comment]
> Update: Passou para TODO

:rocket: Boa

**Comment by overlineink** [comment]
> Update: Passou para TODO

Adiciona os Passos pra Reproducão, aí se precisar de ajuda todos seguem a sua estratégia.

**Comment by acidiney** [comment]
Tem um projecto feito pelo @GentilPinto que é semelhante a essa issue,
podemos compartilhar a codebase.
https://github.com/GentilPinto/provincias_de_angola_api

**Comment by overlineink** [comment]
> Tem um projecto feito pelo @GentilPinto que é semelhante a essa issue,
> podemos compartilhar a codebase.
> https://github.com/GentilPinto/provincias_de_angola_api

Referes-te ao modelo de dados? 👇🏿

```json
{
    "id": 1,
    "nome": "Bengo",
    "capital": "Caxito",
    "municipios": [...]
}
```

**Comment by GentilPinto** [comment]
[I D E I A]
O buscador.ao conta com um endpoint para retornar dados meteorológicos?
Recentemente outros jovens pediram que eu acrescentasse no projecto citado acima e assim o fiz, os dados são extraídos directamente do site do INAMET via web scrapping, o esquema é mais ou menos esse:
`{
"status": 200,
"provincia": "Lunda Sul",
"previsao_de_tempo_actual": {
"Descrição": "Soalheiro",
"Temperatura": "27º",
"Humidade": "27%",
"Vento": "10km/h (180º S)",
"Temperatura Sentida": "26º",
"Temperatura Sentida na Sombra": "26º",
"Precepitação (última hora)": "0 mm",
"Ultra Violetas": "Baixa (1)",
"Cobertura de Nuvens": "0",
"Pressão": "1012 mb"
}
}`

seria fixe se o buscador.ao também tivesse.
O que acham?

**Comment by acidiney** [comment]
@GentilPinto Crie uma nova issue, essa é somente para reportes sobre o endpoint de países, províncias e bairros
